version: '3'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        env_file:
            - .nlp_env
        command: ['/code/deploy/scripts/wait-for-it.sh', 'db:5432', '--', '/code/deploy/scripts/run_develop.sh']
        volumes:
            - .:/code:z
            - ./media:/media:z
            - nlp_data:/code/nlp_data
        ports:
            - '8000:8000'
        depends_on:
            - db

volumes:
    nlp_data:
